config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tasks#home'
  # List all the tasks
  get "tasks", to: "tasks#index"

  # create a new task
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  get "tasks/:id", to: "tasks#show", as: "task"

  get "tasks/:id/edit", to: "tasks#edit", as: "edit_task"
  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy", as: "destroy_task"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :find_task, only: [:show, :edit, :update, :destroy]

    def home
    end
    
    def index
        @tasks = Task.all
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new(params_task)
        @task.save
        redirect_to tasks_path(@tasks)
    end
    
    def edit
    end
    
    def update
        @task.update(params_task)
        redirect_to tasks_path(@tasks)
    end
    
    def show
    end
    
    def destroy
        @task.destroy
        redirect_to tasks_path(@tasks)
    end

    def find_task
        @task = Task.find(params[:id])
    end

    private

    def params_task
        params.require(:task).permit(:title, :details, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit an existing task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed%>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/home.html.erb
<h1>Welcome to my Task Manager App</h1>
<div><%= link_to "List my Tasks", tasks_path %></div>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>Task <%= task.id %>: <%= link_to task.title, task_path(task) %></li>
    <li>Details: <%= task.details %></li>
    <li>Completed: <%= task.completed %></li>
    <br>
  <% end %>
</ul>

<%= link_to "Add a task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>
<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1>Task Selected</h1>

<h2><%= @task.title %></h2>
<%= link_to "Task List", tasks_path %>
<%= link_to "Edit Task", edit_task_path %>
<%= link_to "Delete #{@task.title}",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>